title: John Walters
description: Data Scientist Extraordinaire

url: http://http://johnmwalters.github.io/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: johnmwalters
   twitter: jackmwalters
   facebook: 
   email: johnmwalters@gmail.com

google_analytics: ""
